name: "✅ Feature Request"
description: Suggest an idea or possible new feature for this project.
title: "Feature: "
body:
  - type: markdown
    attributes:
      value: |
        Thanks you for taking the time to fill out this feature request report!
        We kindly ask that you search to see if an [issue already exists](https://github.com/YOCOING/YOCO/issues) for your feature.
        We are also happy to accept contributions from our users. For more details see [here](https://github.com/YOCOING/YOCO/blob/dev/CONTRIBUTING.md).

  - type: textarea
    attributes:
      label: Description
      description: |
        Describe the solution you'd like. A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Summary
      description: |
        Summarize your issue if it is possible.

  - type: textarea
    attributes:
      label: Additional Context
      description: |
        Add any other context about the problem here.
    validations:
      required: false
