name: 'Thanks Comment on PR'

on:
  pull_request_target:
    types: [opened]
    branches:
      - dev

jobs:
  comment:
    if: github.base_ref == 'dev'
    runs-on: ubuntu-latest
    steps:
      - name: Comment PR
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Thank you for contributing to the project. Please note that it may take several days for the Pull Request to be reviewed and approved by the reviewer.
          token: ${{ secrets.GITHUB_TOKEN }}
