name: Release Workflow on PR Merge

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  create-release:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main' && github.event.pull_request.head.ref == 'dev'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Extract version from package.json
        id: package_version
        run: echo "::set-output name=version::$(node -p "require('./package.json').version")"

      - name: Create Git tag
        run: |
          git tag v${{ steps.package_version.outputs.version }}
          git push origin v${{ steps.package_version.outputs.version }}

      - name: Extract Changelog for Current Version
        id: changelog
        run: |
          VERSION=${{ steps.package_version.outputs.version }}
          awk -v ver=$VERSION '/^## \[' ver '\]/,/^## \[[0-9]/{print}' CHANGELOG.md
          echo "::set-output name=content::$(<temp_changelog.md)"
        shell: bash

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ steps.package_version.outputs.version }}
          release_name: Release v${{ steps.package_version.outputs.version }}
          body: ${{ steps.changelog.outputs.content }}
